name: Deploy Flutter Web

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DEPLOY_REPO: 21km43/flutter-web-sample

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.27.1

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web

      - name: Checkout Deployment Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.DEPLOY_REPO }}
          token: ${{ secrets.SOMEONE_PAT }}
          path: deploy_repo

      - name: Copy Build Files
        run: |
          cp -r build/web/* deploy_repo/

      - name: Commit and Push Changes
        run: |
          cd deploy_repo
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "deploy new version"
          git push
